#re-run pipeline
name: blmsv1-feature-branch-pipeline
on:
  push:
    branches-ignore:
      - 'main'
      - 'releases**'
jobs:
build and test:
  sonarqube-scan:
  name: SonarQube Scan
  runs-on: [self-hosted, onprem]

  steps:
   - run: echo "SonarQube scanned"
     
 docker-build-and-push:
  name: Docker Build And Push
  runs-on: [self-hosted, onprem]

  steps:
   - run: echo "Docker build and push"
     

 deploy-app-dev:
  name: Deploy App to Dev Rancher Cluster
  runs-on: [self-hosted, onprem]
  needs: [docker-build-and-push]

  steps:
   - run: echo "Deploy to Dev"